services:
  web:
    container_name: rumor-party-line
    restart: always
    build: .
    ports:
      - '11000:3000'
    networks:
      - internal
    environment:
      PORT: '3000'
      CLIENT_URL: 'https://rumor.orangemayhem.net'
      MAX_PARTY_LINES: '1'
      INITIAL_RUMOR: '...nothing has been said, yet.'
      ENVIRONMENT: 'production'
      DOCKER: 'true'

networks:
  internal:
    external: false